# Generated by Django 5.2.12 on 2026-04-14 20:17

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxsystem", "0001_init_v3"),
    ]

    operations = [
        migrations.AddField(
            model_name="alliancepaymentaccount",
            name="last_notification",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="corporationpaymentaccount",
            name="last_notification",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
