# Generated by Django 4.2.11 on 2025-02-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxsystem", "0002_filterdate_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filteramount",
            options={
                "default_permissions": (),
                "verbose_name": "Filter Amount",
                "verbose_name_plural": "Filter Amounts",
            },
        ),
        migrations.AlterModelOptions(
            name="filterdate",
            options={
                "default_permissions": (),
                "verbose_name": "Filter Date",
                "verbose_name_plural": "Filter Dates",
            },
        ),
        migrations.AlterModelOptions(
            name="filterreason",
            options={
                "default_permissions": (),
                "verbose_name": "Filter Reason",
                "verbose_name_plural": "Filter Reasons",
            },
        ),
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access this app"),
                    ("manage_access", "Can access tools Tax System"),
                    ("create_access", "Can add Corporation"),
                    ("manage_own_corp", "Can manage own Corporation"),
                    ("manage_corps", "Can manage all Corporations"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="smartfilter",
            options={
                "default_permissions": (),
                "verbose_name": "Smart Filter Binding",
                "verbose_name_plural": "Smart Filters Catalog",
            },
        ),
        migrations.AlterModelOptions(
            name="smartgroup",
            options={"default_permissions": ()},
        ),
    ]
