# Generated by Django 5.2.12 on 2026-04-16 18:51

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxsystem", "0002_alliancepaymentaccount_last_notification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allianceowner",
            name="tax_message",
            field=models.TextField(
                blank=True,
                default="Your deposit has fallen to a negative balance. Please settle the outstanding amount immediately to avoid any penalties.",
                help_text="Message that is sent to members when a tax payment is due.",
            ),
        ),
        migrations.AddField(
            model_name="corporationowner",
            name="tax_message",
            field=models.TextField(
                blank=True,
                default="Your deposit has fallen to a negative balance. Please settle the outstanding amount immediately to avoid any penalties.",
                help_text="Message that is sent to members when a tax payment is due.",
            ),
        ),
    ]
