# Generated by Django 4.2.11 on 2025-02-06 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('authentication', '0024_alter_userprofile_language'),
        ('taxsystem', '0002_corporationwalletdivision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='active',
        ),
        migrations.RemoveField(
            model_name='members',
            name='id',
        ),
        migrations.RemoveField(
            model_name='members',
            name='member',
        ),
        migrations.RemoveField(
            model_name='members',
            name='name',
        ),
        migrations.RemoveField(
            model_name='members',
            name='payment_notification',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='payment_member',
        ),
        migrations.AddField(
            model_name='members',
            name='character_id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='character_name',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owneraudit',
            name='last_update_members',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='taxsystem.owneraudit'),
        ),
        migrations.AlterField(
            model_name='members',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('missing', 'Missing')], default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='owneraudit',
            name='corporation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eveonline.evecorporationinfo'),
        ),
        migrations.AlterField(
            model_name='owneraudit',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('pending', 'Pending'), ('failed', 'Failed')], default='', max_length=10, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PaymentSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='', max_length=10, verbose_name='Status')),
                ('notice', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='authentication.userprofile')),
            ],
            options={
                'verbose_name': 'Tax Payment System',
                'verbose_name_plural': 'Tax Payment Systems',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_user', to='taxsystem.paymentsystem'),
            preserve_default=False,
        ),
    ]
