# Generated by Django 4.2.11 on 2025-02-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "taxsystem",
            "0003_alter_filteramount_options_alter_filterdate_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="approver_text",
            field=models.TextField(
                blank=True, help_text="Reason for approval or rejection", null=True
            ),
        ),
    ]
