# Generated by Django 4.2.11 on 2025-02-14 19:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taxsystem", "0004_payments_approver_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="approver_text",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="notified",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="payment_date",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="payment_user",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="system",
        ),
        migrations.RemoveField(
            model_name="paymentsystem",
            name="payment_pool",
        ),
        migrations.AddField(
            model_name="payments",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="taxsystem.paymentsystem",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payments",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                    ("needs_approval", "Needs Approval"),
                ],
                default="pending",
                max_length=16,
                verbose_name="Request Status",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="reviser",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reviser that approved or rejected the payment",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="paymentsystem",
            name="deposit",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Deposit Pool in ISK. Max 16 Digits",
                max_digits=16,
                validators=[
                    django.core.validators.MaxValueValidator(9999999999999999),
                    django.core.validators.MinValueValidator(-9999999999999999),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="paymentsystem",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("deactivated", "Deactivated"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="paymentsystem",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date of the action",
                        verbose_name="Date",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("Status Changed", "Status Changed"),
                            ("Payment Added", "Payment Added"),
                            ("Reviser Comment", "Reviser Comment"),
                        ],
                        default="",
                        help_text="Action performed",
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="Comment"),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("pending", "Pending"),
                            ("rejected", "Rejected"),
                            ("needs_approval", "Needs Approval"),
                        ],
                        help_text="New Status of the action",
                        max_length=16,
                        verbose_name="New Status",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        help_text="Payment that the action was performed on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="taxsystem.payments",
                        verbose_name="Payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User that performed the action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="AdminLogs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date of the action",
                        verbose_name="Date",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("Added", "Added"),
                            ("Changed", "Changed"),
                            ("Deleted", "Deleted"),
                        ],
                        default="",
                        help_text="Action performed",
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="Comment"),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        help_text="Payment that the action was performed on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="taxsystem.owneraudit",
                        verbose_name="Payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User that performed the action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
