# Generated by Django 5.2.13 on 2026-05-03 18:51

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxsystem", "0004_alter_allianceowner_tax_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allianceowner",
            name="tax_message",
            field=models.TextField(
                blank=True,
                default="Your deposit has fallen to a negative balance. Please settle the outstanding amount immediately to avoid any penalties.",
                help_text="Message that is sent to alliance members when a tax payment is overdue or the deposit has fallen below zero.",
            ),
        ),
        migrations.AlterField(
            model_name="corporationowner",
            name="tax_message",
            field=models.TextField(
                blank=True,
                default="Your deposit has fallen to a negative balance. Please settle the outstanding amount immediately to avoid any penalties.",
                help_text="Message that is sent to corporation members when a tax payment is overdue or the deposit has fallen below zero.",
            ),
        ),
    ]
