# Generated by Django 4.2.11 on 2025-02-12 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taxsystem", "0004_payments_approver_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="system",
            field=models.CharField(
                blank=True,
                choices=[("automatic", "System")],
                default="",
                help_text="System that processed the payment",
                max_length=16,
                verbose_name="System",
            ),
        ),
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date of the action",
                        verbose_name="Date",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("canceled", "Canceled"),
                            ("created", "Created"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("deleted", "Deleted"),
                            ("viewed", "Viewed"),
                            ("updated", "Updated"),
                            ("undo", "Undo"),
                        ],
                        help_text="Action performed",
                        max_length=16,
                        verbose_name="Action",
                    ),
                ),
                (
                    "log",
                    models.TextField(help_text="Log of the action", verbose_name="Log"),
                ),
                (
                    "level",
                    models.CharField(
                        help_text="Level of the log",
                        max_length=16,
                        verbose_name="Level",
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        help_text="Corporation that the action was performed on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="taxsystem.owneraudit",
                        verbose_name="Corporation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User that performed the action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
