# Generated by Django 5.2.13 on 2026-07-13 17:41

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0026_alter_characterownership_user_and_more"),
        ("taxsystem", "0005_alter_allianceowner_tax_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allianceadminhistory",
            name="user",
            field=models.ForeignKey(
                help_text="User that performed the action",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="authentication.user",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="alliancepaymentaccount",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="authentication.user",
            ),
        ),
        migrations.AlterField(
            model_name="alliancepaymenthistory",
            name="user",
            field=models.ForeignKey(
                help_text="User that performed the action",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="authentication.user",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="corporationadminhistory",
            name="user",
            field=models.ForeignKey(
                help_text="User that performed the action",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="authentication.user",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="corporationpaymentaccount",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="authentication.user",
            ),
        ),
        migrations.AlterField(
            model_name="corporationpaymenthistory",
            name="user",
            field=models.ForeignKey(
                help_text="User that performed the action",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="authentication.user",
                verbose_name="User",
            ),
        ),
    ]
