# Generated by Django 5.2.13 on 2026-07-20 20:09

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxsystem", "0006_alter_allianceadminhistory_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allianceadminhistory",
            name="owner",
            field=models.ForeignKey(
                help_text="Owner that the action was performed on",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ts_alliance_admin_history",
                to="taxsystem.allianceowner",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="alliancepaymentaccount",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ts_alliance_tax_accounts",
                to="taxsystem.allianceowner",
            ),
        ),
        migrations.AlterField(
            model_name="corporationadminhistory",
            name="owner",
            field=models.ForeignKey(
                help_text="Owner that the action was performed on",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ts_corporation_admin_history",
                to="taxsystem.corporationowner",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="corporationpaymentaccount",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ts_corporation_tax_accounts",
                to="taxsystem.corporationowner",
            ),
        ),
    ]
