# Generated by Django 5.2.13 on 2026-07-21 09:35

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxsystem", "0007_alter_allianceadminhistory_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allianceadminhistory",
            name="target",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("account", "Tax Account"),
                    ("filter", "Filter"),
                    ("filter_set", "Filter Set"),
                    ("payment", "Payment"),
                ],
                default="",
                help_text="Type of the action",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="corporationadminhistory",
            name="target",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("account", "Tax Account"),
                    ("filter", "Filter"),
                    ("filter_set", "Filter Set"),
                    ("payment", "Payment"),
                ],
                default="",
                help_text="Type of the action",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
