# Generated by Django 5.2.13 on 2026-09-06 08:47

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groupmanagement", "0021_alter_authgroup_group_and_more"),
        ("taxsystem", "0009_alter_allianceadminhistory_target_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporationGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the corporation group",
                        max_length=255,
                        verbose_name="Group Name",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        help_text="Groups that will not be taxed",
                        related_name="ts_corporation_aa_groups",
                        to="groupmanagement.group",
                        verbose_name="Groups",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Owner of the corporation group",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ts_corporation_groups",
                        to="taxsystem.corporationowner",
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
