# Generated by Django 5.2.13 on 2026-09-06 11:41

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxsystem", "0010_corporationgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allianceadminhistory",
            name="target",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("account", "Tax Account"),
                    ("corporation", "Corporation"),
                    ("filter", "Filter"),
                    ("filter_set", "Filter Set"),
                    ("payment", "Payment"),
                    ("settings", "Settings"),
                    ("group", "Group"),
                ],
                default="",
                help_text="Type of the action",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="corporationadminhistory",
            name="target",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("account", "Tax Account"),
                    ("corporation", "Corporation"),
                    ("filter", "Filter"),
                    ("filter_set", "Filter Set"),
                    ("payment", "Payment"),
                    ("settings", "Settings"),
                    ("group", "Group"),
                ],
                default="",
                help_text="Type of the action",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
