# Generated by Django 5.2.13 on 2026-09-20 14:04

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxsystem", "0011_alter_allianceadminhistory_target_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access the Tax System"),
                    ("create_access", "Can add Corporation/Alliance"),
                    ("manage_own_corp", "Can manage own Corporation"),
                    ("manage_corps", "Can manage all Corporations"),
                    ("manage_own_alliance", "Can manage own Alliance"),
                    ("manage_alliances", "Can manage all Alliances"),
                ),
                "verbose_name": "AA-TaxSystem",
                "verbose_name_plural": "AA-TaxSystem",
            },
        ),
    ]
