# Generated by Django 5.2.13 on 2026-10-08 16:21

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0026_alter_characterownership_user_and_more"),
        ("taxsystem", "0013_usersettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alliancepaymentaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="authentication.user",
            ),
        ),
        migrations.AlterField(
            model_name="corporationpaymentaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="authentication.user",
            ),
        ),
        migrations.AddConstraint(
            model_name="alliancepaymentaccount",
            constraint=models.UniqueConstraint(
                fields=("owner", "user"),
                name="unique_alliance_payment_account_per_owner_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="corporationpaymentaccount",
            constraint=models.UniqueConstraint(
                fields=("owner", "user"),
                name="unique_corporation_payment_account_per_owner_user",
            ),
        ),
    ]
