# Generated by Django 4.2.26 on 2025-11-20 13:03

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxsystem", "0015_alter_general_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="corporationpayments",
            old_name="corporation_id",
            new_name="owner_id",
        ),
        migrations.AlterField(
            model_name="allianceupdatestatus",
            name="section",
            field=models.CharField(
                choices=[
                    ("payment_system", "Payment System"),
                    ("payments", "Payments"),
                    ("payday", "Payday"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="corporationupdatestatus",
            name="section",
            field=models.CharField(
                choices=[
                    ("division_names", "Wallet Division Names"),
                    ("division", "Wallet Division"),
                    ("wallet", "Wallet Journal"),
                    ("members", "Members"),
                    ("payment_system", "Payment System"),
                    ("payments", "Payments"),
                    ("payday", "Payday"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="corporationpayments",
            name="owner_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID of the owner (corporation or alliance) associated with this payment",
                null=True,
            ),
        ),
    ]
